### ISSUE TITLE
circuit-breaker functional locally, but doesn't get deployed to OpenShift

### ISSUE THREAD

**Issue by aakella1** [nodeshift-starters/nodejs-circuit-breaker#12]
Two issues
1. We are getting a security vulnerability issue (but the localhost version ran even with the issue)
nsp check
(+) 1 vulnerability found

2. OpenShift/Minishift deploy failing

Please find log below
```txt
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'openshift' ]
2 info using npm@5.5.1
3 info using node@v9.2.1
4 verbose run-script [ 'preopenshift', 'openshift', 'postopenshift' ]
5 info lifecycle nodejs-circuit-breaker-name@0.0.1~preopenshift: nodejs-circuit-breaker-name@0.0.1
6 info lifecycle nodejs-circuit-breaker-name@0.0.1~openshift: nodejs-circuit-breaker-name@0.0.1
7 verbose lifecycle nodejs-circuit-breaker-name@0.0.1~openshift: unsafe-perm in lifecycle true
8 verbose lifecycle nodejs-circuit-breaker-name@0.0.1~openshift: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Applications/software/projects/node-install-demo/nodejs-circuit-breaker/name-service/node_modules/.bin:.:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/Applications/software/tools/apache-maven-3.3.9/bin:/Applications/software/rh/oc-v3.7.9/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle nodejs-circuit-breaker-name@0.0.1~openshift: CWD: /Applications/software/projects/node-install-demo/nodejs-circuit-breaker/name-service
10 silly lifecycle nodejs-circuit-breaker-name@0.0.1~openshift: Args: [ '-c', 'nodeshift --osc.strictSSL=false' ]
11 silly lifecycle nodejs-circuit-breaker-name@0.0.1~openshift: Returned: code: 1  signal: null
12 info lifecycle nodejs-circuit-breaker-name@0.0.1~openshift: Failed to exec openshift script
13 verbose stack Error: nodejs-circuit-breaker-name@0.0.1 openshift: `nodeshift --osc.strictSSL=false`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid nodejs-circuit-breaker-name@0.0.1
15 verbose cwd /Applications/software/projects/node-install-demo/nodejs-circuit-breaker/name-service
16 verbose Darwin 15.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "openshift"
18 verbose node v9.2.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error nodejs-circuit-breaker-name@0.0.1 openshift: `nodeshift --osc.strictSSL=false`
22 error Exit status 1
23 error Failed at the nodejs-circuit-breaker-name@0.0.1 openshift script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by aakella1** [comment]
Lance

I see a button missing in the OpenShift deployment....another issue in GitHub?

Best Regards
Anand Akella
Senior Specialist Solutions Architect 
Middleware Solutions | South East Enterprise 
aakella@redhat.com | (404)386-1228
www.redhat.com

**Comment by lance** [comment]
@aakella1 I don't see that. Can you elaborate?

![screen shot 2017-12-12 at 2 33 48 pm](https://user-images.githubusercontent.com/15952/33904455-9589077c-df49-11e7-9853-fed0423adc3c.png)

**Comment by aakella1** [comment]
Was that local deployment or OpenShift? I had problems deploying to Minishift/OpenShift...check screenshot
(Apologies...Not the button, but STATUS shown next to "Name service/Operational state-OK" is missing)
    On Tuesday, December 12, 2017, 2:34:46 PM EST, Lance Ball <notifications@github.com> wrote:  
 
 
@aakella1 I don't see that. Can you elaborate?

**Comment by lance** [comment]
@aakella1 I cannot seem to recreate this on either minishift or running on localhost.
